import { useState, useSyncExternalStore } from 'react'
import { ScenePanel } from '../scene/ScenePanel'
import { createWeek07Store } from '../app/week07-store'
import { quantity } from '../platform'
import type { EngineeringRecordFieldId } from '../platform/lessons/engineering-steps'
import { createWeek07EngineeringRecord, createWeek07Draft, reviseWeek07Record, canRunWeek07Model, runWeek07Model, saveWeek07Draft, loadWeek07Draft, exportWeek07Submission, defaultBlankWeek07Artifact, validateStudentArtifact, verifyStudentArtifact, type StudentLabArtifact, type Week07Draft, type Week07Inputs } from './lab'
import { renderWeek07Responses, WEEK07_FIELD_PROMPTS, WEEK07_SUPPLIED_SETUP } from './responses'
import './week07.css'
import { GitHubSave } from './GitHubSave'
const KEY='aerolab-week07-v1'
const guidedModelText=JSON.stringify({schemaVersion:'week07.student-model/v1',id:'week07-student-model',version:'1.0.0',slots:[{id:'controls.demand',expressions:[{name:'requiredMoment',expression:'',unit:'N*m'}]},{id:'controls.effectiveness',expressions:[{name:'dynamicPressure',expression:'',unit:'Pa'},{name:'deltaCm',expression:'',unit:'1'},{name:'deltaMoment',expression:'',unit:'N*m'}]}]},null,2)
function fresh() {return createWeek07Draft(createWeek07EngineeringRecord(crypto.randomUUID(),'1',{moduleId:'controls',modelId:defaultBlankWeek07Artifact.id,version:'1.0.0'},WEEK07_SUPPLIED_SETUP,guidedModelText))}
function download(name:string,text:string,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
const sections=['Understand','Model','Predict','Implement and check','Conclude'] as const
export function Week07Lab(){
 const [loaded]=useState(()=>{try{return loadWeek07Draft(localStorage,KEY)}catch(error){return {draft:null,error:String(error)}}})
 const [draft,setDraft]=useState<Week07Draft>(()=>loaded.draft??fresh())
 const [section,setSection]=useState(0),[message,setMessage]=useState(loaded.error??'Draft ready. Browser storage is not a GitHub submission.')
 const [lectureHref]=useState(()=>{try{const id=localStorage.getItem('week07-return-slide');return '/teaching/week07/student.html'+(id?.startsWith('W07-')?'#'+encodeURIComponent(id):'')}catch{return '/teaching/week07/student.html'}})
 const [store,setStore]=useState(()=>createWeek07Store()),[show,setShow]=useState(true),[verified,setVerified]=useState('Not run for this model')
 const snapshot=useSyncExternalStore(store.subscribe,store.getSnapshot,store.getSnapshot)
 const [experiment,setExperiment]=useState<'baseline'|'zero-target'|'half-speed'|'zero-elevator'>('baseline')
 function persist(next:Week07Draft){setDraft(next);try{saveWeek07Draft(localStorage,KEY,next);setMessage('Draft saved in this browser. Click Save to GitHub to commit and push.')}catch(error){setMessage('Local save failed: '+String(error)+' Export your work now.')}}
 function change(field:EngineeringRecordFieldId,text:string){persist({...draft,record:reviseWeek07Record(draft.record,String(Number(draft.record.revision)+1),{[field]:text})})}
 function modelText(text:string){const withoutVerification={...draft};delete withoutVerification.verification;persist({...withoutVerification,artifact:defaultBlankWeek07Artifact,record:reviseWeek07Record(draft.record,String(Number(draft.record.revision)+1),{},text)});setStore(createWeek07Store());setVerified('Not run for this edited model. Earlier results remain bound to their original revisions.')}
 function readArtifact():StudentLabArtifact {const a=JSON.parse(draft.record.modelText) as StudentLabArtifact;const errors=Object.values(validateStudentArtifact(a)).flat();if(errors.length)throw new Error(errors.join(' '));return a}
 function inputs():Week07Inputs {const s=store.getSnapshot().state;return {pitchInertia:s.massProperties.pitchInertia,requestedAcceleration:s.modules.controls!.requestedAcceleration,competingMoment:s.modules.controls!.competingMoment,density:s.environment.density,airspeed:s.motion.airspeed,referenceArea:s.modules.controls!.referenceArea,referenceChord:s.modules.controls!.referenceChord,elevatorDerivative:s.modules.controls!.elevatorDerivative,elevatorAngle:s.controls.elevatorCommanded} as Week07Inputs}
 function run(){try{if(!canRunWeek07Model(draft.record))throw new Error('Complete physics, assumptions, model and prediction before running.');const artifact=readArtifact();const next=createWeek07Store(artifact);const id=crypto.randomUUID();const command=experiment==='half-speed'?{type:'SET_AIRSPEED',payload:{value:quantity(20,'m/s',id)}}:experiment==='zero-elevator'?{type:'SET_ELEVATOR',payload:{value:quantity(0,'rad',id)}}:experiment==='zero-target'?{type:'SET_MODULE_STATE',payload:{moduleId:'controls',field:'requestedAcceleration',value:quantity(0,'rad/s^2',id)}}:null;if(command){const r=next.dispatch({id,...command,source:'lesson',context:{scenarioId:'week07-student',model:next.getSnapshot().activeModels[0]??null}},{id,source:'student-entered',description:'Week07 selected investigation',derivedFrom:[]});if(!r.ok)throw new Error(r.error)}
 const s=next.getSnapshot().state;const values={...inputs(),airspeed:s.motion.airspeed,elevatorAngle:s.controls.elevatorCommanded,requestedAcceleration:s.modules.controls!.requestedAcceleration} as Week07Inputs
 const record={...draft.record,model:{moduleId:'controls',modelId:artifact.id,version:artifact.version}}
 const result=runWeek07Model(crypto.randomUUID(),record,artifact,values);setStore(next);persist({...draft,record,artifact,runs:[...draft.runs,result]});setMessage(`Recorded ${experiment} run. Aircraft shows your model's applied response.`)
 }catch(error){setStore(createWeek07Store());setMessage('Cannot run: '+String(error))}}
 function brief(){if(!canRunWeek07Model(draft.record)){setMessage('Complete physics, assumptions, model and prediction first.');return}const text=`ENGINEERING IMPLEMENTATION BRIEF — Week07\nImplement only student-owned JSON; do not edit platform code. Do not fill missing decisions.\n${Object.entries(draft.record.fields).filter(([k])=>k!=='execution').map(([k,v])=>k+': '+v.text).join('\n')}\nReturn {schemaVersion:"week07.student-model/v1",id,version,slots:[{id:"controls.demand",expressions:[{name:"requiredMoment",expression:"...",unit:"N*m"}]},{id:"controls.effectiveness",expressions:[{name:"dynamicPressure",expression:"...",unit:"Pa"},{name:"deltaCm",expression:"...",unit:"1"},{name:"deltaMoment",expression:"...",unit:"N*m"}]}]}.\nApproved inputs: pitchInertia (kg*m^2), requestedAcceleration (rad/s^2), competingMoment (N*m), density (kg/m^3), airspeed (m/s), referenceArea (m^2), referenceChord (m), elevatorDerivative (1/rad), elevatorAngle (rad).\nUse + - * / parentheses, constants, inputs and named intermediates only. No JavaScript. Angles arrive in radians. Check baseline, zero target, half speed, zero elevator and signs.\n`;download('week07-implementation-brief.txt',text)}
 function currentSubmission(){let artifact=draft.artifact;try{artifact=JSON.parse(draft.record.modelText)}catch{/* Keep incomplete source text for honest submission. */}return exportWeek07Submission({...draft,artifact})}
 function exportDraft(){download('submission.json',JSON.stringify(currentSubmission(),null,2))}
 function exportResponses(){download('responses.md',renderWeek07Responses(currentSubmission()),'text/markdown');setMessage('Downloaded responses.md from the current draft.')}
 async function importSubmission(file:File){if(file.size>500000){setMessage('Submission file exceeds 500 KB.');return}try{const raw=JSON.parse(await file.text()) as {record?:Week07Draft['record'];model?:StudentLabArtifact;runs?:Week07Draft['runs'];verification?:Week07Draft['verification']};const candidate={revision:raw.record?.revision,record:raw.record,artifact:raw.model,runs:raw.runs,verification:raw.verification};const checked=loadWeek07Draft({getItem:()=>JSON.stringify(candidate),setItem:()=>{}},'import');if(!checked.draft)throw new Error(checked.error??'Invalid submission.');persist(checked.draft);setStore(createWeek07Store());setMessage('Imported saved submission and restored its recorded runs.')}catch(error){setMessage('Cannot import submission: '+String(error))}}
 const field=(id:EngineeringRecordFieldId)=><label key={id} className="lab-field"><strong>{id==='aiUse'?'AI use':id}</strong><span>{WEEK07_FIELD_PROMPTS[id]}</span><textarea aria-label={id} value={draft.record.fields[id].text} onChange={e=>change(id,e.target.value)} /></label>
 const displayed=snapshot.state.outputs.controls
 const panel=<section className="week07-panel" aria-label="Week07 guided lab"><p className="eyebrow">WEEK 07 · INDIVIDUAL · 90 MINUTES</p><h2>{sections[section]}</h2><nav aria-label="Engineering sections">{sections.map((s,i)=><button key={s} aria-current={section===i?'step':undefined} onClick={()=>setSection(i)}>{i+1}. {s}</button>)}</nav><p role="status">{message}</p><GitHubSave submission={currentSubmission()} />
 {section===0&&<><h3>Supplied starting condition</h3>{Object.entries(WEEK07_SUPPLIED_SETUP).map(([k,v])=><p key={k}><strong>{k} · instructor supplied</strong><br/>{v}</p>)}<p>Your work fills two missing calculations. Until you run a valid model, the aircraft has no student-computed response.</p>{field('physics')}</>}
 {section===1&&<><p>Demand: control moment plus competing moment equals inertia times target acceleration. Effectiveness: dynamic pressure × area × chord × coefficient increment.</p><p>q∞ = ½ρV²; ΔCm = Cmδ × δe. Convert display degrees to radians using π/180. The model receives radians.</p>{field('assumptions')}{field('model')}</>}
 {section===2&&<><p>This is an implementation prediction using the principles just taught, not an unseen examination. Save it before running your model.</p>{field('prediction')}</>}
 {section===3&&<><button onClick={brief} disabled={!canRunWeek07Model(draft.record)}>Export implementation brief</button>{!canRunWeek07Model(draft.record)&&<p>First complete physics, assumptions, model and prediction.</p>}<label className="lab-field">Model JSON / expression editor<textarea aria-label="Model JSON" spellCheck={false} value={draft.record.modelText} onChange={e=>modelText(e.target.value)}/></label><label>Import model JSON<input aria-label="Import model JSON" type="file" accept=".json" onChange={async e=>{const f=e.target.files?.[0];if(f){if(f.size>100000){setMessage('Model file exceeds 100 KB.');return}modelText(await f.text())}}}/></label><label>Import saved submission<input aria-label="Import saved submission" type="file" accept=".json" onChange={e=>{const f=e.target.files?.[0];if(f)void importSubmission(f)}}/></label><p>Without AI, enter your expressions in the same JSON editor. Only arithmetic and approved variable names are allowed.</p><label>Investigation<select aria-label="Investigation" value={experiment} onChange={e=>setExperiment(e.target.value as typeof experiment)}><option value="baseline">Baseline: 40 m/s, −5°, target +0.12</option><option value="zero-target">Changed target: 0 rad/s²</option><option value="half-speed">Changed speed: 20 m/s</option><option value="zero-elevator">Zero elevator</option></select></label><p>Each run restores the supplied baseline, then changes only the selected input.</p><button disabled={!canRunWeek07Model(draft.record)} onClick={run}>Run my model</button><button disabled={!canRunWeek07Model(draft.record)} onClick={()=>{try{const r=verifyStudentArtifact(readArtifact());setVerified(r.detail);persist({...draft,verification:{modelHash:draft.record.modelHash,checkedAt:new Date().toISOString(),...r}})}catch(error){setVerified(String(error))}}}>Run verification checks</button><p>{verified}</p><div aria-label="Student results">{(['requiredMoment','deltaCm','deltaMoment','achievedAcceleration'] as const).map(k=><p key={k}>{{requiredMoment:'Required control moment',deltaCm:'Coefficient increment ΔCm',deltaMoment:'Elevator moment',achievedAcceleration:'Achieved acceleration'}[k]}: {displayed?.[k]?.status==='known'?`${displayed[k].value.toPrecision(6)} ${displayed[k].unit}`:'Unavailable — no valid student result'}</p>)}{displayed?.deltaMoment?.status === 'known' && draft.runs.length > 0 && draft.runs[draft.runs.length-1]!.record.modelHash === draft.record.modelHash && draft.runs[draft.runs.length-1]!.result['controls.effectiveness'].values.dynamicPressure?.value !== undefined&&<p>Dynamic pressure: {draft.runs[draft.runs.length-1]!.result['controls.effectiveness'].values.dynamicPressure?.value.toPrecision(6)} Pa</p>}</div>{field('verification')}<details><summary>Preserved runs ({draft.runs.length})</summary>{draft.runs.map(r=><p key={r.id}>Run {r.id.slice(0,8)} · record revision {r.record.revision} · {r.record.modelHash}</p>)}</details></>}
 {section===4&&<>{field('claim')}{field('reflection')}{field('aiUse')}<h3>Submit reproducible work</h3><p>Click Save to GitHub. It writes submission.json and responses.md into student/, commits them, and pushes to your fork. Submit your fork URL and the saved commit shown above. Export buttons below are a backup if GitHub is unavailable.</p><p>Incomplete work can be exported. A saved file does not mean verification passed.</p></>}
 <footer><button onClick={()=>setSection(Math.max(0,section-1))} disabled={section===0}>Previous section</button><button onClick={()=>setSection(Math.min(4,section+1))} disabled={section===4}>Next section</button><button onClick={exportDraft}>Export submission</button><button onClick={exportResponses}>Export responses.md</button></footer><p>Record revision {draft.record.revision}. Earlier runs remain bound to their original model and prediction.</p></section>
 return <div className="studio"><header className="studio-header"><h1>Week07 Controls Lab</h1><a href={lectureHref} target="week07-lecture">Lecture</a><a href="#">Exit lab</a><button onClick={()=>setShow(!show)}>{show?'Hide controls':'Show controls'}</button></header><main className="studio-main"><ScenePanel store={store} snapshot={snapshot} showControls={show} hideSceneTools hidePitchVisuals={false} inspector={()=>panel}/></main></div>
}
