// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest'
import { afterEach, expect, it } from 'vitest'
import { cleanup, fireEvent, render, screen } from '@testing-library/react'
import { App } from '../../src/app/App'
import { createAppCatalog } from '../../src/app/catalog'
import { createParameterStore } from '../../src/app/parameter-workspace'

afterEach(cleanup)

it('runs the Week 06 prediction, experiment, reveal, reset, navigation, and exit flow', () => {
  const store = createParameterStore()
  render(<App store={store} catalog={createAppCatalog()} />)
  expect(screen.getAllByRole('button', { name: 'Start Week06 lesson' }).length).toBeGreaterThan(0)
  fireEvent.click(screen.getAllByRole('button', { name: 'Start Week06 lesson' })[0]!)
  expect(screen.getByText('Stage 1 of 6')).toBeVisible()
  expect(screen.getByRole('heading', { name: 'Fixed reference example: worked baseline' })).toBeVisible()
  const workedExample = screen.getByLabelText('Worked Stage 1 baseline example')
  expect(workedExample).toHaveTextContent('5000 kg·m²')
  expect(workedExample).toHaveTextContent('+1350 N·m − 750 N·m = +600 N·m')
  expect(screen.getByText('Fixed reference example: worked baseline').compareDocumentPosition(screen.getByRole('heading', { name: 'Your prediction' }))).toBe(Node.DOCUMENT_POSITION_FOLLOWING)
  expect(screen.queryByText(/With a zero target, \+750 N·m/)).not.toBeInTheDocument()
  expect(screen.queryByLabelText('Requested pitch acceleration')).not.toBeInTheDocument()
  expect(screen.getByRole('button', { name: 'Experiment history · 1' })).toBeDisabled()
  fireEvent.change(screen.getByLabelText('Prediction'), { target: { value: 'Demand falls because the target falls.' } })
  fireEvent.click(screen.getByRole('button', { name: 'Submit prediction' }))
  expect(screen.getByLabelText('Requested pitch acceleration')).toBeVisible()
  expect(screen.getByRole('button', { name: 'Reveal explanation' })).toBeDisabled()
  fireEvent.change(screen.getByLabelText('Requested pitch acceleration'), { target: { value: '0' } })
  fireEvent.click(screen.getByRole('button', { name: 'Set Requested pitch acceleration' }))
  expect(store.getSnapshot().lesson?.experimentCount).toBe(1)
  expect(screen.getByLabelText('Target requirement')).toHaveTextContent('750 N*m')
  expect(screen.getByLabelText('Target requirement')).toHaveTextContent('250 N')
  expect(screen.getByLabelText('Applied response')).toHaveTextContent('450 N')
  expect(screen.getByLabelText('Applied response')).toHaveTextContent('600 N*m')
  expect(screen.getByLabelText('Applied response')).toHaveTextContent('0.12 rad/s^2')
  expect(screen.queryByRole('button', { name: 'Apply required tail force' })).not.toBeInTheDocument()
  expect(screen.queryByText(/With a zero target, \+750 N·m/)).not.toBeInTheDocument()
  fireEvent.click(screen.getByRole('button', { name: 'Reveal explanation' }))
  expect(screen.getByText(/With a zero target, \+750 N·m/)).toBeVisible()
  expect(screen.getByLabelText('Observed readings')).toBeVisible()
  fireEvent.click(screen.getByRole('button', { name: 'Apply required tail force' }))
  expect(store.getSnapshot().lesson?.experimentCount).toBe(2)
  expect(store.getSnapshot().state.loads.pitchMoment).toMatchObject({ status: 'known', value: 0 })
  expect(store.getSnapshot().state.outputs.controls?.achievedAcceleration).toMatchObject({ status: 'known', value: 0 })
  expect(screen.getByLabelText('Applied response')).toHaveTextContent('250 N')
  expect(screen.getByLabelText('Applied response')).toHaveTextContent('0 N*m')
  expect(screen.getByLabelText('Applied response')).toHaveTextContent('0 rad/s^2')
  fireEvent.click(screen.getByRole('button', { name: 'Top' }))
  const inspector = document.getElementById('aircraft-inspector')!
  inspector.scrollTop = 240
  fireEvent.click(screen.getByRole('button', { name: 'Next stage' }))
  expect(screen.getByText('Stage 2 of 6')).toBeVisible()
  expect(inspector.scrollTop).toBe(0)
  expect(screen.getByRole('button', { name: 'Top' })).toHaveAttribute('aria-pressed', 'true')
  fireEvent.click(screen.getByRole('button', { name: 'Previous stage' }))
  expect(store.getSnapshot().state.modules.controls?.tailForce).toMatchObject({ status: 'known', value: 450 })
  expect(store.getSnapshot().lesson?.prediction).toBeNull()
  expect(screen.queryByRole('button', { name: 'Apply required tail force' })).not.toBeInTheDocument()
  fireEvent.change(screen.getByLabelText('Prediction'), { target: { value: 'Zero acceleration requires balancing the competing moment.' } })
  fireEvent.click(screen.getByRole('button', { name: 'Submit prediction' }))
  fireEvent.change(screen.getByLabelText('Requested pitch acceleration'), { target: { value: '0' } })
  fireEvent.click(screen.getByRole('button', { name: 'Set Requested pitch acceleration' }))
  fireEvent.click(screen.getByRole('button', { name: 'Reveal explanation' }))
  fireEvent.click(screen.getByRole('button', { name: 'Next stage' }))
  fireEvent.change(screen.getByLabelText('Prediction'), { target: { value: 'This draft should be cleared.' } })
  fireEvent.click(screen.getByRole('button', { name: 'Reset stage' }))
  expect(store.getSnapshot().lesson).toMatchObject({ stageId: 'elevator-response', prediction: null, revealed: false, experimentCount: 0 })
  expect(screen.getByLabelText('Prediction')).toHaveValue('')
  fireEvent.click(screen.getByRole('button', { name: 'Exit lesson' }))
  expect(store.getSnapshot().lesson).toBeNull()
  expect(screen.getByText('Exploratory workspace')).toBeVisible()
})

it('lists Week 06 in the registered course catalog', () => {
  render(<App store={createParameterStore()} catalog={createAppCatalog()} />)
  fireEvent.click(screen.getByRole('button', { name: 'Course & status' }))
  expect(screen.getByText('Week 06 · Pitch control: demand, response, authority')).toBeVisible()
  expect(screen.getAllByRole('button', { name: 'Start Week06 lesson' }).length).toBeGreaterThan(1)
})

it('keeps the Stage 1 applied force unchanged until it is explicitly applied and restores the baseline on reset', () => {
  const store = createParameterStore()
  render(<App store={store} catalog={createAppCatalog()} />)
  fireEvent.click(screen.getAllByRole('button', { name: 'Start Week06 lesson' })[0]!)
  expect(screen.queryByLabelText('Requested pitch acceleration')).not.toBeInTheDocument()
  fireEvent.change(screen.getByLabelText('Prediction'), { target: { value: 'The requirement changes before the applied force does.' } })
  fireEvent.click(screen.getByRole('button', { name: 'Submit prediction' }))
  fireEvent.change(screen.getByLabelText('Requested pitch acceleration'), { target: { value: '0' } })
  fireEvent.click(screen.getByRole('button', { name: 'Set Requested pitch acceleration' }))
  expect(screen.getByLabelText('Target requirement')).toHaveTextContent('750 N*m')
  expect(screen.getByLabelText('Applied response')).toHaveTextContent('450 N')
  expect(screen.getByLabelText('Applied response')).toHaveTextContent('600 N*m')
  fireEvent.click(screen.getByRole('button', { name: 'Reveal explanation' }))
  fireEvent.click(screen.getByRole('button', { name: 'Apply required tail force' }))
  expect(screen.getByLabelText('Applied response')).toHaveTextContent('250 N')
  fireEvent.click(screen.getByRole('button', { name: 'Reset stage' }))
  expect(store.getSnapshot().lesson).toMatchObject({ stageId: 'signed-moment', prediction: null, revealed: false, experimentCount: 0 })
  expect(store.getSnapshot().state.modules.controls?.tailForce).toMatchObject({ value: 450 })
  expect(store.getSnapshot().state.loads.pitchMoment).toMatchObject({ value: 600 })
  expect(store.getSnapshot().state.outputs.controls?.achievedAcceleration).toMatchObject({ value: 0.12 })
})
