// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest'
import { afterEach, expect, it, vi } from 'vitest'
import { cleanup, fireEvent, render, screen, act } from '@testing-library/react'
import { App } from '../../src/app/App'
import { createAppCatalog } from '../../src/app/catalog'
import { createParameterStore } from '../../src/app/parameter-workspace'
afterEach(() => { cleanup(); vi.useRealTimers() })
it('loads, plays fixed steps, pauses on force input, reinitializes and restores the baseline', () => {
  vi.useFakeTimers()
  const store = createParameterStore()
  render(<App store={store} catalog={createAppCatalog()} />)
  fireEvent.click(screen.getByRole('button', { name: 'Load C2 example' }))
  expect(store.getSnapshot().state.loads.pitchMoment).toMatchObject({ value: 600 })
  fireEvent.click(screen.getByRole('button', { name: 'Play pitch' }))
  act(() => { vi.advanceTimersByTime(100) })
  expect(store.getSnapshot().state.simulation.elapsedTime).toMatchObject({ value: 0.1 })
  fireEvent.change(screen.getByLabelText('Tail force (+ down)'), { target: { value: '0' } })
  fireEvent.click(screen.getByRole('button', { name: 'Set Tail force (+ down)' }))
  expect(store.getSnapshot().state.simulation.status).toBe('paused')
  expect(store.getSnapshot().state.loads.pitchMoment).toMatchObject({ value: -750 })
  fireEvent.click(screen.getByRole('button', { name: 'Reinitialize pitch' }))
  expect(store.getSnapshot().state.motion.pitch).toMatchObject({ value: 0 })
  fireEvent.click(screen.getByRole('button', { name: 'Reset scenario' }))
  expect(store.getSnapshot().state.modules.controls?.tailForce).toMatchObject({ value: 450 })
  fireEvent.click(screen.getByRole('button', { name: 'Return to empty workspace' }))
  expect(store.getSnapshot().state.simulation.status).toBe('unconfigured')
})
it('C3 numeric elevator edits update the shared command and aerodynamic readouts', () => {
  const store = createParameterStore()
  render(<App store={store} catalog={createAppCatalog()} />)
  fireEvent.click(screen.getByRole('button', { name: 'Load C3 elevator example' }))
  const input = screen.getByLabelText('Elevator (deg)')
  fireEvent.change(input, { target: { value: '5' } })
  fireEvent.click(screen.getByRole('button', { name: 'Set Elevator (deg)' }))
  expect(store.getSnapshot().state.controls.elevatorCommanded).toMatchObject({ value: Math.PI / 36 })
  const moment = store.getSnapshot().state.outputs.controls?.deltaMoment
  expect(moment?.status === 'known' && moment.value).toBeCloseTo(-1642.005760276)
  fireEvent.click(screen.getByRole('button', { name: 'Elevator plots' }))
  expect(screen.getByRole('img', { name: 'Elevator moment versus speed' })).toBeVisible()
  fireEvent.click(screen.getByRole('button', { name: 'Reset scenario' }))
  expect(store.getSnapshot().state.motion.airspeed).toMatchObject({ value: 40 })
})
it('rejects invalid airspeed locally, restores active value, and keeps plot scales fixed', () => {
  const store = createParameterStore()
  render(<App store={store} catalog={createAppCatalog()} />)
  fireEvent.click(screen.getByRole('button', { name: 'Load C3 elevator example' }))
  const input = screen.getByLabelText('Airspeed (m/s)')
  const before = store.getSnapshot()
  fireEvent.change(input, { target: { value: '-10' } })
  fireEvent.click(screen.getByRole('button', { name: 'Set Airspeed (m/s)' }))
  expect(input).toHaveValue(40)
  expect(screen.getByRole('alert')).toHaveTextContent('Active value restored')
  expect(store.getSnapshot()).toBe(before)
  fireEvent.click(screen.getByRole('button', { name: 'Elevator plots' }))
  const plot = screen.getByRole('img', { name: 'Elevator moment versus angle' })
  expect(plot).toHaveAttribute('data-scale', '15000')
  fireEvent.change(input, { target: { value: '80' } })
  fireEvent.click(screen.getByRole('button', { name: 'Set Airspeed (m/s)' }))
  expect(plot).toHaveAttribute('data-scale', '15000')
  expect(screen.getAllByLabelText('Current operating point')).toHaveLength(2)
  expect(screen.queryByRole('slider', { name: 'elevator deflection slider' })).not.toBeInTheDocument()
})
it('preserves comparison scale across dock navigation and labels elevator-only moments', () => {
  const store = createParameterStore()
  render(<App store={store} catalog={createAppCatalog()} />)
  fireEvent.click(screen.getByRole('button', { name: 'Load C3 elevator example' }))
  fireEvent.click(screen.getByRole('button', { name: 'Elevator plots' }))
  fireEvent.change(screen.getByLabelText(/Vertical scale/), { target: { value: '5000' } })
  fireEvent.click(screen.getByRole('button', { name: 'Pitch response' }))
  fireEvent.click(screen.getByRole('button', { name: 'Elevator plots' }))
  expect(screen.getByRole('img', { name: 'Elevator moment versus angle' })).toHaveAttribute('data-scale', '5000')
  expect(screen.getByText(/Elevator contribution only; net moment/)).toBeVisible()
  fireEvent.click(screen.getByRole('button', { name: 'Reset scenario' }))
  expect(screen.getByRole('img', { name: 'Elevator moment versus angle' })).toHaveAttribute('data-scale', '5000')
})
it('offers recovery after disabling Controls without resetting the experiment', () => {
  const store = createParameterStore()
  render(<App store={store} catalog={createAppCatalog()} />)
  fireEvent.click(screen.getByRole('button', { name: 'Load C3 elevator example' }))
  fireEvent.click(screen.getByRole('button', { name: 'Modules' }))
  fireEvent.click(screen.getByRole('button', { name: 'Disable Control Authority' }))
  expect(screen.getByRole('button', { name: 'Play pitch' })).toBeDisabled()
  fireEvent.click(screen.getByRole('button', { name: 'Resume controls module' }))
  expect(screen.getByRole('button', { name: 'Play pitch' })).toBeEnabled()
  fireEvent.click(screen.getByRole('button', { name: 'Step 0.02 s' }))
  expect(store.getSnapshot().state.simulation.elapsedTime).toMatchObject({ value: 0.02 })
})
it('renders a bounded history page while retaining every event for replay', () => {
  const store = createParameterStore()
  store.dispatch({ id: 'load', type: 'RESET_SCENARIO', payload: { scenarioId: 'c2-pitch-example' }, source: 'pointer', context: { scenarioId: 'parameter-workspace', model: null } })
  for (let i = 0; i < 41; i++) store.dispatch({ id: `step-${i}`, type: 'STEP_SIMULATION', payload: null, source: 'system', context: { scenarioId: 'c2-pitch-example', model: null } })
  const { container } = render(<App store={store} catalog={createAppCatalog()} />)
  fireEvent.click(screen.getByRole('button', { name: /Experiment history/ }))
  expect(container.querySelectorAll('.experiment-history li')).toHaveLength(20)
  fireEvent.click(screen.getByRole('button', { name: 'Older' }))
  expect(container.querySelectorAll('.experiment-history li')).toHaveLength(20)
  fireEvent.click(screen.getByRole('button', { name: 'Latest · live' }))
  expect(store.getSnapshot().events).toHaveLength(42)
})
it('C4 exposes limits with degree conversion, shows its envelope and preserves the chosen plot scale', () => {
  const store = createParameterStore()
  render(<App store={store} catalog={createAppCatalog()} />)
  fireEvent.click(screen.getByRole('button', { name: 'Load C4 authority example' }))
  expect(screen.getByText(/A nominal deflection can meet the target/)).toBeVisible()
  fireEvent.click(screen.getByRole('button', { name: 'Elevator plots' }))
  expect(screen.getByRole('img', { name: 'Elevator authority versus deflection' })).toBeVisible()
  fireEvent.change(screen.getByLabelText('Vertical scale (±N·m)'), { target: { value: '5000' } })
  fireEvent.click(screen.getByRole('button', { name: 'Model setup' }))
  fireEvent.change(screen.getByLabelText('Actuator travel ±'), { target: { value: '2' } })
  fireEvent.click(screen.getByRole('button', { name: 'Set Actuator travel ±' }))
  expect(store.getSnapshot().state.modules.controls?.actuatorLimit).toMatchObject({ value: 2 * Math.PI / 180 })
  expect(store.getSnapshot().state.loads.pitchMoment.status).toBe('unconfigured')
  fireEvent.click(screen.getByRole('button', { name: 'Inputs' }))
  expect(screen.getByText(/Selected deflection exceeds usable travel/)).toBeVisible()
  fireEvent.click(screen.getByText('Pitch playback · fixed selected deflection'))
  expect(screen.getByRole('button', { name: 'Play pitch' })).toBeDisabled()
  fireEvent.click(screen.getByRole('button', { name: 'Reset scenario' }))
  expect(store.getSnapshot().state.loads.pitchMoment.status).toBe('known')
  expect(screen.getByRole('img', { name: 'Elevator authority versus deflection' })).toHaveAttribute('data-scale', '5000')
})
it('C4 applies the nominal target through the store and keeps rate planning separate from playback', () => {
  const store = createParameterStore()
  render(<App store={store} catalog={createAppCatalog()} />)
  fireEvent.click(screen.getByRole('button', { name: 'Load C4 authority example' }))
  expect(screen.getByRole('button', { name: 'Play pitch' })).not.toBeVisible()
  fireEvent.click(screen.getByRole('button', { name: 'Use nominal target deflection' }))
  expect(store.getSnapshot().state.outputs.controls?.achievedAcceleration).toMatchObject({ status: 'known' })
  expect(screen.getByText('Selected deflection meets the target in the nominal model.')).toBeVisible()
  const result = store.getSnapshot().state.outputs.controls?.achievedAcceleration
  expect(result?.status === 'known' && result.value).toBeCloseTo(0.12)
  fireEvent.click(screen.getByRole('button', { name: 'Rate plan' }))
  expect(screen.getByText(/does not drive elevator motion/)).toBeVisible()
  const before = store.getSnapshot().state.controls.elevatorCommanded
  fireEvent.change(screen.getByLabelText('Planning start pose'), { target: { value: '2' } })
  fireEvent.click(screen.getByRole('button', { name: 'Set Planning start pose' }))
  expect(store.getSnapshot().state.controls.elevatorCommanded).toEqual(before)
  fireEvent.click(screen.getByRole('button', { name: 'Elevator plots' }))
  expect(screen.getByRole('img', { name: 'Elevator authority versus deflection' })).toHaveAttribute('data-scale', '5000')
  fireEvent.click(screen.getByLabelText('Compare uncertainty band'))
  expect(document.querySelector('[aria-label="Bounded effectiveness uncertainty"]')).not.toBeNull()
  fireEvent.click(screen.getByLabelText('Show separate rate-plan interval'))
  expect(document.querySelector('[aria-label="Separate planning reachable interval"]')).not.toBeNull()
})
