export { PLATFORM_API_VERSION } from './version'
export { CANONICAL_UNITS, quantity, unconfigured } from './units/types'
export type { CanonicalUnit, EngineeringValue, KnownQuantity, UnconfiguredQuantity } from './units/types'
export { engineeringToRender, renderToEngineering } from './coordinates/transforms'
export type { EngineeringVector, RenderVector } from './coordinates/transforms'
export { CANONICAL_QUANTITIES, CANONICAL_QUANTITY_IDS } from './state/quantities'
export type { PhysicalState, CanonicalQuantityId } from './state/quantities'
export { createUnconfiguredAircraftState } from './state/types'
export type { AircraftState } from './state/types'
export type { CommandEnvelope, CoreCommand, CoreCommandPayloads, CommandSource } from './commands/types'
export type { SimulationState } from './simulation/types'
export { createModuleRegistry, RegistrationError } from './module-system/registry'
export type { EngineeringModuleDescriptor, DescriptorCatalog, DescriptorRegistry } from './module-system/types'
export { createLessonRegistry } from './lessons/registry'
export type { LessonDescriptor, LessonStageDescriptor, ScenarioDefinition } from './lessons/types'
export { ENGINEERING_STEPS } from './lessons/engineering-steps'
export type { EngineeringStepId, EngineeringRecordFieldId, EngineeringRequirements } from './lessons/engineering-steps'
export type { ModelReference, ModelResultEvidence, FidelityLevel } from './evidence/types'
export type { ProvenanceId, ProvenanceRecord, CommitProvenance } from './provenance/types'
export { createAircraftStore, readQuantity, replayEvents } from './state/store'
export type { AircraftStore, StoreSnapshot, CommandEvent, DispatchResult, StoreOptions, LessonRuntimeState } from './state/store'
export { degreesToRadians, radiansToDegrees } from './units/conversions'

export { createModuleRuntime } from './module-system/runtime'
export type { ModuleRuntime, ModulePackage, ModuleEvaluation, VisualizationDeclaration } from './module-system/runtime'
